### ISSUE TITLE
Vector Files do not properly render

### ISSUE THREAD

**Issue by fortepc** [SilphRoad/silph-league#2]
#1 's pull added SVG files that do not properly render. This problem applies to both the pikachu (january) and the dratini (february) vector badges, but for the purpose of this issue report I'm only looking at the dratini badge. 

https://imgur.com/Il5wkeY - Chrome Renders it like this

https://imgur.com/vWPpOdU - Adobe Illustrator renders it like this
https://imgur.com/yIqAs8m - One of the errors that illustrator shows when placing it
https://imgur.com/i7eBVSS - Another error that shows up when illustrator when placing it

https://imgur.com/XgCgpNR - Inkscape renders it like this
https://imgur.com/aKq9a45 - Error that shows up when trying to open it in Inkscape

@tanah, I'm looking at the source for the SVG, and it looks like a few images were linked instead of embedded.

I'm looking at silph-league/assets/2018-02-24-community-day/badge.svg and these are all the linked files that aren't available when trying to import it.
 `/home/tana/workspace/silph-league/assets/2018-02-24-community-day/badge.png`
`/home/tana/Descargas/community-day-2018-01.png` 
`file:///home/tana/Descargas/community-day-2018-01.png`
`/home/tana/Descargas/SurfsUpPikachu10px.png`
`file:///home/tana/Descargas/SurfsUpPikachu10px.png`

Also, the font, referenced for the vector, `Garage Gothic`, isn't a default font on my windows PC, nor is it present in the silph-league/fonts/ directory

**Comment by tanahy** [comment]
Understood, I'll remove the embedded files, turn the text to paths. 
Please let me know if the errors keep happening when I reupload them.
